ENGAGEMENT_GENERATION_VERSION = "synthetic_engagement_v1"
DEFAULT_ENGAGEMENT_SEED = 42

# Utilities are converted to probabilities with a logistic function. These
# coefficients belong only to the synthetic-world engagement mechanism.
FAVORITE_INTERCEPT = -2.65
FAVORITE_PREFERENCE_WEIGHT = 1.55
FAVORITE_NOVELTY_WEIGHT = 0.30
FAVORITE_RARITY_WEIGHT = 0.30
FAVORITE_LUXURY_WEIGHT = 0.22
FAVORITE_REPEAT_WEIGHT = 0.42
FAVORITE_NOISE_STDDEV = 0.85

CART_INTERCEPT = -3.20
CART_PREFERENCE_WEIGHT = 1.25
CART_IMPULSIVENESS_WEIGHT = 0.90
CART_REPEAT_WEIGHT = 0.34
CART_FAVORITE_BONUS = 0.72
CART_PRICE_PENALTY = 0.28
CART_POPULARITY_WEIGHT = 0.12
CART_NOISE_STDDEV = 0.90

PURCHASE_INTERCEPT = -4.30
PURCHASE_PREFERENCE_WEIGHT = 1.15
PURCHASE_IMPULSIVENESS_WEIGHT = 1.25
PURCHASE_REPEAT_WEIGHT = 0.38
PURCHASE_FAVORITE_BONUS = 0.85
PURCHASE_CART_BONUS = 2.45
PURCHASE_PRICE_PENALTY = 0.48
PURCHASE_POPULARITY_WEIGHT = 0.08
PURCHASE_NOISE_STDDEV = 1.00

FAVORITE_DELAY_PROBABILITY = 0.24
CART_DELAY_PROBABILITY = 0.28
PURCHASE_DELAY_PROBABILITY = 0.42
MAX_DELAY_DAYS = 7
